### ISSUE TITLE
Typewriter on Firefox is slightly buggy

### ISSUE THREAD

**Issue by impulse** [Insax/savetheinternet#86] opened 2018-06-15 20:38 UTC
Is slightly buggy and may need some extra fixed in css

**Comment by jerptrs** [comment] 2018-06-15 20:42
On which version are you? I'm on `60.0.2` and the Typewriter looks and works fine for me.

**Comment by weswaldix** [comment] 2018-06-15 20:49
Here on 60.0.2. The 'a' in "Save the Internet" is jumping a little bit.

**Comment by aytic** [comment] 2018-06-15 20:55
@jerptrs 
https://i.imgur.com/dPSFflD.png
Left Firefox, right Chrome
Top spacing is slightly off also the text is slightly jumping on firefox
Version 60.0.2
4.16.13-2-ARCH

**Comment by jerptrs** [comment] 2018-06-15 20:59
Oh yep you are right. Haven't noticed it until now.

**Comment by weswaldix** [comment] 2018-06-15 22:07
Has anyone figured out the problem?

**Comment by FlorianMaak** [comment] 2018-06-15 22:32
Can't reproduce this with FF 61.0b10. Seems to be a bug, that's already fixed in nightly-build?
![comp](https://user-images.githubusercontent.com/6325146/41492024-b8da4520-70fc-11e8-9a3d-06b05e3a25dd.png)

**Comment by aytic** [comment] 2018-06-15 23:44
@FlorianMaak is the text moving at any point? Seems to be a bug then yeah

**Comment by FlorianMaak** [comment] 2018-06-16 00:09
It's working 100% like Chrome. You can take two screenshots and you have the exactly same appearance.
But I think we should implement a workaround, if you're on the latest stable and having this issues. 
It's a shorttime-project and we need to support the current generation of browsers :/

Nightly takes to long, to get merged into release-circle.

**Closed** 2019-08-27 07:02 UTC
Labels: about-page, enhancement, visual
